### ISSUE TITLE
Looking for model for smaller resolution video, or a way to train my own onnx

### ISSUE THREAD

**Issue by trevorvanhoof** [digital-standard/ThreeDPoseUnityBarracuda#11]
I'm really impressed with the quality, but performance is a bit low, around 15 fps at the 448x448 pixels.
I notice the model stops working at other resolutions, onnx filename contains 448x448 so that is probably why! :)
but at 224x224 it is a full 60 FPS so I would like to try a resolution like that.

This was by far the easiest project to use and (highest performance so far on a project that actually works) so I would really like to use it on the project I'm working on.

**Comment by yukihiko** [comment]
Thank you. I consider the high specs required to be a challenge, but I believe the hardware is advancing faster than I can try.

**Comment by MyzTyn** [comment]
@trevorvanhoof  Have you found way to train onnx? If yes, then can you tell me how to?

**Comment by trevorvanhoof** [comment]
sadly not, i have found azure kinect and modern ipad can provide similar data, not hardware independent like this but just fyi
