### ISSUE TITLE
AssertionException: Assertion failure. Values are not equal. Expected: 3 == 4

### ISSUE THREAD

**Issue by Francegala** [digital-standard/ThreeDPoseUnityBarracuda#17]
not sure if still maintained but this is the error I'm getting. Everything is up to date both Unity and Barracuda but still no fix found.
System:
MacBook Pro (16-inch, 2019)
2.6 GHz 6-Core Intel Core i7
32 GB 2667 MHz DDR4
AMD Radeon Pro 5500M 8 GB
Unity 2019 4 12 f1

AssertionException: Assertion failure. Values are not equal.
Expected: 3 == 4
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertBase.cs:29)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertGeneric.cs:31)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertGeneric.cs:19)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Assertions/Assert/AssertPrimitiveTypes.cs:176)
Unity.Barracuda.PrecompiledComputeOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.0.3/Barracuda/Runtime/Core/Backends/BarracudaPrecompiledCompute.cs:625)
Unity.Barracuda.StatsOps.Unity.Barracuda.IOps.Conv2D (Unity.Barracuda.Tensor X, Unity.Barracuda.Tensor K, Unity.Barracuda.Tensor B, System.Int32[] stride, System.Int32[] pad, Unity.Barracuda.Layer+FusedActivation fusedActivation) (at Library/PackageCache/com.unity.barracuda@1.0.3/Barracuda/Runtime/Core/Backends/StatsOps.cs:69)
Unity.Barracuda.GenericWorker+<StartManualSchedule>d__29.MoveNext () (at Library/PackageCache/com.unity.barracuda@1.0.3/Barracuda/Runtime/Core/Backends/GenericWorker.cs:211)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
VNectBarracudaRunner:UpdateVNectModel() (at Assets/Scripts/VNectBarracudaRunner.cs:242)
VNectBarracudaRunner:Update() (at Assets/Scripts/VNectBarracudaRunner.cs:173)

![image](https://user-images.githubusercontent.com/7479492/96151168-06e63200-0f03-11eb-9d6a-d8411e0e1bf5.png)

**Comment by yukihiko** [comment]
see:
https://github.com/digital-standard/ThreeDPoseUnityBarracuda/issues/15

**Comment by Francegala** [comment]
Thanks a lot, just for future reference, it fails on MacOs but it works on Windows machines.
