### ISSUE TITLE
Questions about the pretrained onnx model and 3 inputs

### ISSUE THREAD

**Issue by fooWally** [digital-standard/ThreeDPoseUnityBarracuda#39]
Dear Author,
Thank you for your open source code.
I have been studying pose estimation and unity c# with your code as a practitioner.
and I have a couple of questions about the pretrained model named "Resnet34_3inputs_448x448....onnx"
To see the model input/output and its architecture, I uploaded the onnx file to netron app. It displays 3 inputs and your VnectBarracudaRunner.cs also uses 3 inputs. My question is what does your code do with 3 inputs?
and what kind of 3 inputs data did you train the model with?

Best regards 
Foowally

**Comment by fooWally** [comment]
I've got answer from the author
Thank you Yukihiko Aoyagi again ;-)
I can close the issue

**Comment by Holmex** [comment]
> 我已经从作者那里得到答案 再次感谢 Yukihiko Aoyagi ;-) 我可以关闭这个问题

Hello, may I ask how the author replied to you, I also have the following questions, the C# script used to estimate the pose is named VNect, which means that the model used in this article is VNect? Why import a Resnet3_4.onnx model? Is it related to VNect? I hope you can help me
