### ISSUE TITLE
missing script on MainCamera

### ISSUE THREAD

**Issue by fm64hylian** [digital-standard/ThreeDPoseUnityBarracuda#7]
Awesome project, Could you please point out which script is attached to the MainCamera besides CameraMover? 

This also happens on your other ThreeDPose projects. I'm using Windows 10

**Comment by yukihiko** [comment]
It's a Unity capture or spout script. I guess I added it to try and forgot to erase it. It should work just fine without it.

**Comment by fm64hylian** [comment]
Thanks for your reply. I'll remove them from your projects.  It would be nice to update the meta files as well.
