### ISSUE TITLE
Missing UnityChan License Archive

### ISSUE THREAD

**Issue by eims** [digital-standard/ThreeDPoseUnityBarracuda#9]
https://unity-chan.com/contents/license_en/
>3.4 In the event the User redistributes the Digital Asset Data of Company’s Characters distributed by the Company based on the use permitted under Article 3.1, it shall distribute by enclosing a set of separately defined license related files in addition to the indication of the license logo or license sign provided in Article 3.3.

https://unity-chan.com/contents/license_jp/
>利用者が第１項で許諾された利用に基づいて、弊社が配布する弊社キャラクターのデジタルアセットデータを再配布する場合、第３項に定めるライセンスロゴもしくはライセンス表記の掲示に加えて、別途定めるライセンス関連ファイル一式を同梱して配布するものとします。

https://unity-chan.com/download/releaseNote.php?id=UnityChanLicenseDoc

**Comment by h-nakae** [comment]
Hi, sorry and thanks for your advise.
We add the archive file as following.
ThreeDPoseUnityBarracuda/Assets/UCL2_0.zip

And added the information about unitychan license and the logo on read.me as follwing.
![image](https://user-images.githubusercontent.com/56616438/84855210-86234080-b09e-11ea-9f89-f65edd3d2c5a.png)

Is that okay??
regards

**Comment by eims** [comment]
ok
(I closed this by mistake. Sorry.)
